### ISSUE TITLE
Tested on SM-T230 model (It works!)

### ISSUE THREAD

**Issue by Tomodoro** [anthonymesa/T230NU-Arch-Linux#2]
Hello

First of all, thank you very much for this detailed guide. It is intended for the SM-T230NU, but since the models are just slightly different (from what I could find my device does not have an IR Remote nor OTG support) I decided to give it a try.

After following all the steps I obtained a functional archlinux, but there where some steps I had to change because of unexpected problems. Since I don't have an external microSD (I'm planning to buy a 32GB, the maximum allowed by the tablet), I replaced `extSdCard` with `emulated/0`.

The first was the tar unpacking, using the command from the guide tried to load `-C` as a path, so I had to change the order to the following:

```
# tar -xzf /storage/emulated/0/arch.tar.gz -C /storage/emulated/0/chroot
```

I suspect it has to do with the version of busybox I am using. I rooted my device years ago and since then I haven't touched the busybox installation I did.

The second is the creation of the `arch.img`. The first time I installed archlinux successfully and (after setting up the keys) when I ran `pacman -Syu` I couldn't update because I didn't have enough space left. (`121018` blocks needed, `120505` blocks free). I followed all the steps again, but this time I made the `arch.img` of 2 GiB. This change allowed me to update, but when I uninstalled the `linux-armv7` package it released 700 MiB.

I suspect that uninstalling first the kernel and then updating the system would have allowed me to have archlinux inside a 1 GiB `arch.img`, but I am not totally sure if this is true. I installed `ncdu` to check the space and it showed 1 GiB out of 2 GiB in use, with the kernel already uninstalled.

Since I first updated and then uninstalled the kernel and linux-framework (I followed the steps from the guide lineally), checking `/var/cache/pacman/pkg` shows that together this two packages use over 200 MiB in cache. I don't know if this information may be useful in some way, but I wanted to give a complete feedback from my test.

Apart from this little deviations from the guide, everything is running flawlessly!
The screenshot failed for some reason, so I took pictures with another phone.

Regards, Tomodoro.

.
<img src="https://user-images.githubusercontent.com/73404958/123712797-0f885980-d841-11eb-8451-8ccaaf04e57b.jpg" width="800">
<img src="https://user-images.githubusercontent.com/73404958/123712811-14e5a400-d841-11eb-8e16-44580a34954e.jpg" width="400"><img src="https://user-images.githubusercontent.com/73404958/123712823-1a42ee80-d841-11eb-94da-2caee95e2a73.jpg" width="400">

**Comment by Tomodoro** [comment]
An update to my testing.

I managed to get a working VNC and interact with an X session inside a VNC Viewer application. I will try to reproduce my steps.

1. Install [VNC Viewer 3.0.0.023865](https://www.apkmirror.com/apk/realvnc-limited/vnc-viewer/vnc-viewer-3-0-0-023865-release/) (from APK Mirror, not a direct link). The latest version from Google Play Store requires Android 6.0 an up, so I chose the oldest possible for compatibility and performance.
2. Enter the chroot and install the following packages: `tigervnc`, `xorg-server`, `xterm`, `openbox`, `ttf-dejavu`, `ttf-liberation`.
3. Follow the [Initial Setup](https://wiki.archlinux.org/title/TigerVNC#Initial_setup) of tigervnc from the archwiki. Change `lxqt` to `openbox` in the configuration file and change the geometry from `1920x1080` to `1280x720`. Do not try to launch tigervnc with systemd as stated in the following section of the wiki, the command will be ignored for been inside a chroot.
4. Now exit the chroot.

Until now Arch is capable of starting a VNC server and the VNC Viewer application can connect to it, but it will not be able to open an xterm instance (right clicking on the screen and choosing it from the Terminal category). I don't know if it will be able to open any other program installed, but I tracked the specific problem of xterm until I found [this post](https://www.linuxquestions.org/questions/linux-desktop-74/get_pty-not-enough-ptys-error-4175533684/) that suggests the following change.

Replace the following line:
```
# mount -t devpts devpts /storage/extSdCard/chroot/dev/pts/
```
with this one
```
mount -o gid=5,mode=620 -t devpts devpts /storage/extSdCard/chroot/dev/pts/
```

5. Enter again the chroot with this modification.
6. Run `vncserver :X`, where X is the number chosen in `/etc/tigervnc/vncserver.users`.
7. Ignore the `XKEYBOARD` warnings. They state Android-specific actions not found in standard Linux systems. I still haven't figured out how to suppress them.
8. I still haven't figured out the `xinit` and `dbus-updpate-environment` errors, I just mention them for comparation purposes. It also says that `/usr/bin/python` is missing.
9. Minimize Terminal Emulator and open VNC Viewer. The address is `127.0.0.1:590X` where X is the number from step 6, and the password is the one from step 3.

If everything went right, this should be the result (I installed `neofetch` and `netsurf` for demonstration purposes):
![20210629_150629](https://user-images.githubusercontent.com/73404958/123853778-d9ec7a80-d8eb-11eb-9c48-fbad7b0b6cc9.jpg)

The errors from step 8 where the following:
```
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
```
```
dbus-update-activation-environment: error: unable to connect to D-Bus: Using X11 for dbus-daemon autolaunch was disabled at compile time, set yout DBUS_SESSION_BUS_ADDRESS instead
```

That was my test. I don't know if there is another way of getting a graphical environment, but this is the method that Termux states in [its wiki](https://wiki.termux.com/wiki/Graphical_Environment) and I adapted it for this use case.

Regards, Tomodoro

**Comment by anthonymesa** [comment]
Wow! this is a great write-up! I will absolutely include this information in the guide, that or you can create a pull request on the repo and I can merge. Thank you for the help!

**Comment by Tomodoro** [comment]
I really liked the way you organized all the steps in this guide, so I prefer that you include the information in the way you think fits the best.

**Comment by Tomodoro** [comment]
Another update to my testing.

I followed all the guide steps again, this time with a 32GB external microSDHC card. It came with the FAT32 filesystem, so the maximum file size allowed for the disk image was 4GiB. I did not check if the tablet could read exFAT. Every step from the archlinux installation was successful and I was able to get a fully functional Linux chroot. I made some discoveries on the mounting process and for easiness I created 3 scripts.

First script at `/storage/extSdCard/Arch/scripts/setup.txt`
```
su -c losetup /dev/block/loop7 /storage/extSdCard/Arch/arch.img
su -c mount -t ext4 /dev/block/loop7 /storage/extSdCard/Arch/chroot
su -c mount -t proc proc /storage/extSdCard/Arch/chroot/proc/
su -c mount -t sysfs sysfs /storage/extSdCard/Arch/chroot/sys/
```
This mounting process is persistent between Terminal Emulator sessions, there is only need to run the commands when the tablet is rebooted.

Second script at `/storage/extSdCard/Arch/scripts/start.txt`
```
su -c mount -o bind /dev/ /storage/extSdCard/Arch/chroot/dev/
su -c mount -o bind /storage/extSdCard/Arch/shared /storage/extSdCard/Arch/chroot/home/shared
su -c mount -t tmpfs tmpfs /storage/extSdCard/Arch/chroot/tmp/
su -c mount -o gid=5,mode=620 -t devpts devpts /storage/extSdCard/Arch/chroot/dev/pts/
su -c chroot /storage/extSdCard/Arch/chroot /bin/bash -l
```
This mounting process gets undone after exiting the chroot, so I included all the commands before the chrooting.
To ease the transfer of files with the Android host I bind mounted a folder inside the chroot and it has not given me any kind of trouble so far, however I try to avoid inserting files that contain custom permissions.

Thrid script at `/storage/extSdCard/Arch/scripts/profile.txt`
```
alias start="sh /storage/extSdCard/Arch/scripts/start.txt"
alias setup="sh /storage/extSdCard/Arch/scripts/setup.txt"

echo ""
echo "Linux chroot commands"
echo "    start: starts Archlinux chroot"
echo "    setup: mounts loop device"
echo "           only use after a reboot"
echo ""
```
I sourced this file as the *Initial command* on Terminal Emulator to have a fast access to the Linux chroot.

Writing this scripts from a Windows machine did not work well, Terminal Emulator could not read correctly the line breaks and the commands failed, so I decided to write the scripts from an Android app. Because of that I would like to propose [this app](https://billthefarmer.github.io/editor/) to the list in the guide. It is very straightforward for the job and uses under 512KB of space.

Inside archlinux I undid the following commands from the guide
```
# echo "export HOME=/root" >> $STOR/chroot/etc/profile
# echo "cd /root" >> $STOR/chroot/etc/profile
```
because I created an unprivileged user (to build packages from AUR) and it was causing issues with the directories.
However, since the chroot is started simulating a login instance using the file `/.bash_login` has the same effects, so I wrote the following in it.
```
export HOME=/root
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_RUNTIME_DIR=/run/user/$UID
cd /root
```

I made a major improvement to the way the vncserver is started. Since the process needs to run continuously and gets the terminal busy, I decided to run it on `screen` so it is done on the background. To automatize the process of starting and stopping the server without memorizing screen commands I created the script `/usr/local/bin/runvnc` with the following:
```
#!/bin/bash

if [ "$EUID" -ne 0 ] ; then
    echo "Please run as root"
    exit
fi

case "$1" in
    start)
        screen -dmS vnc_server vncserver :0
        ;;
    stop)
        screen -S vnc_server -X stuff "^C"
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        ;;
esac
```
This way the command `runvnc start` will create a background process with the vncserver and `runvnc stop` will finish the process. Since I have an unprivileged account I put the requirement of been root to use the command, because according to some tigervnc bug reports only root can start a server (it did not use to be that way).

I installed `tint2` to keep track of the open windows and configured openbox to load it everytime the vnc server starts with this command:
```
echo "tint2 &" >> /etc/xdg/openbox/autostart
```

I made a manual installation of Texlive and it took less than 150 MiB of space for everything I needed. Apart from that and some dependencies pulled by `texstudio` and `tint2`, I managed to have a minimal Linux workplace. Here are some screenshots I took while connected to the server from my computer.

![Screenshot (499)](https://user-images.githubusercontent.com/73404958/125147297-5820fc00-e0f8-11eb-9a05-9d4988a7596e.png)
![Screenshot (501)](https://user-images.githubusercontent.com/73404958/125147391-d8dff800-e0f8-11eb-984e-fc1f0a353fa4.png)

I think this will be the last test I will make with my device. Following the steps from the guide and making the changes from this comment I acquired a pretty consistent Linux experience inside the tablet. This should close the "issue".

If you find anything of interest from my changes or the scripts I made, please feel free to include them in the guide.

Regards, Tomodoro

**Comment by anthonymesa** [comment]
Thank you so much again for your testing, I will merge this information into the guide also!
